import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import dynamic from "next/dynamic";

import Nav from "../components/nav";
import SafeHydrate from "../components/safehydrate";
import { useAppContext } from "../components/context";
import { useEffect, useState } from "react";
import axios from "axios";

const Graph = dynamic(() => import("../components/graph"), { ssr: false });

const Home: NextPage = () => {
    const context = useAppContext();
    const [address, setAddress] = useState<string>("");
    const [recommendations, setRecommendations] = useState<string[]>([]);
    const [loading, setLoading] = useState<boolean>(false);

    useEffect(() => {
        setAddress(context.address ?? "");
    }, [context]);

    return (
        <div className={styles.container}>
            <Nav />
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div>
                    <h1 className="text-center py-3">Your Recommendations</h1>
                    <div className="mt-1">
                        <div className="mb-2">
                            <input
                                type="text"
                                name="name"
                                id="name"
                                className="h-16 ring-offset-2 ring-2 block w-full sm:text-sm p-4 outline-none"
                                placeholder="Contract Address"
                                value={address}
                                onChange={(e) => setAddress(e.target.value)}
                            />
                        </div>
                        <div className="w-full flex justify-center items-center mt-10">
                            <button
                                style={{
                                    background: "#4287f5",
                                    color: "white",
                                }}
                                className="rounded-md px-4 py-3 text-md"
                                onClick={async () => {
                                    setLoading(true);
                                    const recommendations = await axios.get<
                                        string[]
                                    >("http://localhost:3001/recommend", {
                                        params: { address: address },
                                    });
                                    setRecommendations(recommendations.data);
                                    setLoading(false);
                                }}
                            >
                                Get recommendation
                            </button>
                        </div>
                    </div>
                    <SafeHydrate>
                        <Graph user={address} />
                    </SafeHydrate>
                    <div>
                        {loading ? (
                            <p>Learning your deepest darkest secrets</p>
                        ) : (
                            recommendations.map((el, i) => (
                                <p className="py-1" key={i}>
                                    {i}. {el}
                                </p>
                            ))
                        )}
                    </div>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Based
                </a>
            </footer>
        </div>
    );
};

export default Home;
